# -*- coding: utf-8 -*-
"""Proyecto modulo 5 v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19sGIzfeZwGmUfJQOqbLk_e1ZCeSPjkb5
"""

#-------------------------------------------------------------
# PROYECTO MÓDULO 5 POR SJV
# Dataset: Ventas_sucursales_espana_50_filas_realista_v2.csv
# En este proyecto se siguió el orden de las lecciones indicadas en el documento
# Espero que el orden y sintaxis sea adecuado, me base en las lecciones anteriores
# así como también algunos documentos entregados como apoyo de estudio.
# Algunos elementos tuve que obtenerlos de lectura/recursos complementarios.
#-------------------------------------------------------------

# LIBRERÍAS A UTILIZAR EN ESTE PROYECTO

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# LECCIÓN 1 – ANÁLISIS EXPLORATORIO DE DATOS.

def analisis_datos(df):

    print("\n========== LECCIÓN 1 – ANÁLISIS EXPLORATORIO DE DATOS ==========")

    # Para leer las primeras filas usamos head.
    print("\nPrimeras filas:")
    print(df.head())

    # Para leer las últimas filas usamos tail.
    print("\nÚltimas filas:")
    print(df.tail())

    # Si deseamos saber la info general usamos info.
    print("\nInformación general:")
    df.info()

    # Para tener una descripción del database usamos describe.
    print("\nEstadísticas descriptivas:")
    print(df.describe())

    # Incluimos una descripción de los objetos al especificarlo entre paréntesis.
    print("\nDescripción de objetos:")
    print(df.describe(include="object"))

    # Importante definir el tipo de variables con las que vamos a trabajar.

    print("Variables numéricas:", df.select_dtypes(include="number").columns)
    print("Variables categóricas:", df.select_dtypes(include="object").columns)

    # Si hay valores nulos dentro de los daros podemos obtenerlos con:
    print("\nValores nulos:")
    print(df.isnull().sum())

    # Estos valores serán tratados a través de la función:
    print("\nEliminación de valores nulos:", df.shape)
    df.dropna(inplace=True)
    print("\nValores nulos eliminados:", df.shape)

    return df


# LECCIÓN 2 – CONCEPTOS BÁSICOS DE ESTADÍSTICA DESCRIPTIVA

def estad_desc(df):

    print("\n========== LECCIÓN 2 – ESTADÍSTICA DESCRIPTIVA ==========")

    # Excluimos ID_Venta como variable ya que no tiene un sentido estadístico en los cálculos.
    numeric_df = df.select_dtypes(include=np.number).drop(columns=["ID_Venta"], errors="ignore")

    # Podemos definir las medidas de tendencia central y de dispersión con:
    print("Media:\n", numeric_df.mean())
    print("Mediana:\n", numeric_df.median())
    print("Moda:\n", numeric_df.mode())
    print("Varianza:\n", numeric_df.var())
    print("Desviación std:\n", numeric_df.std())

    # Calculamos los cuartiles o percentiles a través de:
    print("Cuartiles:\n", numeric_df.quantile([0.25, 0.5, 0.75]))

    # Para conocer la frecuencia de algo podemos usar un histograma para represemtarlo:
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    numeric_df.hist(figsize=(12, 8), bins=20, edgecolor="black", color="#69b3a2")
    plt.suptitle("Distribución de variables numéricas", fontsize=16)
    plt.show()

    # Para detectar valores atípicos (outliers) podemos usar un gráfico boxplot:
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    plt.figure(figsize=(12, 6))
    sns.boxplot(data=numeric_df, palette="Set3")
    plt.title("Detección de valores atípicos en variables numéricas", fontsize=14)
    plt.xticks(rotation=45)
    plt.show()

    return df


# LECCIÓN 3 – CORRELACIÓN

def correlac_data(df):

    print("\n========== LECCIÓN 3 – CORRELACIÓN ==========")

    from scipy.stats import pearsonr

    # Decidimos convertir las variables a numéricas por seguridad de los cálculos.

    df["Cantidad"] = pd.to_numeric(df["Cantidad"], errors="coerce")
    df["Precio_Unitario"] = pd.to_numeric(df["Precio_Unitario"], errors="coerce")
    df["Total"] = pd.to_numeric(df["Total"], errors="coerce")

    # Excluimos ID_Venta para que no afecte la correlación

    numeric_df = df.select_dtypes(include=np.number).drop(columns=["ID_Venta"], errors="ignore")

    # Podemos crear una Matriz de correlación general que se represente por un heatmap:
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    plt.figure(figsize=(8,6))
    sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm", linewidths=0.5)
    plt.title("Matriz de Correlación", fontsize=14)
    plt.show()

    # Aplicamos el coeficiente de Pearson para cuantificar la correlación entre variables:
    # Creamos dos cálculos para tener un mayor conocimiento del estado y así comparar.

    # Cantidad vs Total
    r1, p1 = pearsonr(df["Cantidad"], df["Total"])

    print("\nCantidad vs Total")
    print("Coeficiente de Pearson:", r1)
    print("Valor p:", p1)

    # Precio_Unitario vs Total
    r2, p2 = pearsonr(df["Precio_Unitario"], df["Total"])

    print("\nPrecio_Unitario vs Total")
    print("Coeficiente de Pearson:", r2)
    print("Valor p:", p2)

    # Interpretación automática de los datos obtenidos en esta sección:

    def interpretar(r, p, variable):
        if abs(r) > 0.7:
            fuerza = "fuerte"
        elif abs(r) > 0.4:
            fuerza = "moderada"
        else:
            fuerza = "débil"

        if p < 0.05:
            significancia = "Estadísticamente significativa"
        else:
            significancia = "Estadísticamente NO significativa"

        print(f"Correlación {fuerza} y {significancia} para {variable}")

    interpretar(r1, p1, "Cantidad")
    interpretar(r2, p2, "Precio_Unitario")

    return df


# LECCIÓN 4 – REGRESIONES LINEALES

def regres_lineal(df):

    print("\n========== LECCIÓN 4 – REGRESIONES LINEALES ==========")

    # Necesitaremos acudir a statsmodels para poder crear una regresión lineal
    # Así mismo llamaremos al cálculo de elementos fundamentales.

    import statsmodels.api as sm
    from sklearn.metrics import mean_squared_error, mean_absolute_error

    # Regresión simple (Cantidad - Total)

    X_simple = sm.add_constant(df["Cantidad"])
    y = df["Total"]

    model_simple = sm.OLS(y, X_simple).fit()

    print("\n--- Regresión Simple (Cantidad - Total) ---")
    print(model_simple.summary())

    # Acudimos a seaborn.regplot para generar una visualización de esta relación.
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    plt.figure(figsize=(8, 6))
    sns.regplot(
        x="Cantidad",
        y="Total",
        data=df,
        scatter_kws={"alpha": 0.5, "color": "#4C72B0"},
        line_kws={"color": "red", "linewidth": 2})
    plt.title("Regresión lineal: Cantidad vs Total", fontsize=14)
    plt.xlabel("Cantidad")
    plt.ylabel("Total (€)")
    plt.show()

    pred_simple = model_simple.predict(X_simple)

    # Podemos evaluar el modelo con los siguientes parámetros de prueba:

    print("MSE:", mean_squared_error(y, pred_simple))
    print("MAE:", mean_absolute_error(y, pred_simple))
    print("R2:", model_simple.rsquared)


    # Regresión múltiple (Cantidad - Precio_Unitario - Total)

    X_multiple = df[["Cantidad", "Precio_Unitario"]]
    X_multiple = sm.add_constant(X_multiple)

    model_multiple = sm.OLS(y, X_multiple).fit()

    print("\n--- Regresión Múltiple (Cantidad + Precio_Unitario → Total) ---")
    print(model_multiple.summary())
    print("R2 modelo múltiple:", model_multiple.rsquared)

    return df


# LECCIÓN 5 – ANÁLISIS VISUAL DE DATOS

def visual_data(df):

    print("\n========== LECCIÓN 5 – ANÁLISIS VISUAL DE DATOS ==========")

    # Excluimos ID_Venta de las visualizaciones numéricas
    numeric_df = df.select_dtypes(include=np.number).drop(columns=["ID_Venta"], errors="ignore")

    # Podemos crear un Pairplot personalizado para detectar patrones.
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    g = sns.pairplot(numeric_df, corner=True, diag_kind="kde",
        plot_kws={"alpha": 0.6, "color": "#4C72B0"},
        diag_kws={"color": "#55a868"})
    g.fig.suptitle("Relaciones entre variables numéricas", fontsize=16)
    g.fig.subplots_adjust(top=0.95)
    plt.show()

    # Otro recurso valioso es Jointplot personalizado que también se usa para detectar patrones.
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    g = sns.jointplot(data=df, x="Cantidad", y="Total", kind="reg", height=7,
        scatter_kws={"alpha": 0.5, "color": "#4C72B0"},
        line_kws={"color": "red", "linewidth": 2})
    g.fig.suptitle("Cantidad vs Total", fontsize=14)
    g.fig.subplots_adjust(top=0.95)
    plt.show()

    # Por otro lado Violinplot se utiliza para la evaluar la densidad de las ventas por sucursal.
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    plt.figure(figsize=(10, 5))
    sns.violinplot(data=df, x="Sucursal", y="Total", inner="quart", palette="Set2")
    plt.title("Densidad de Ventas por Sucursal")
    plt.show()

    # Así mismo FacetGrid se usa para hacer una segmentación por Región.
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    g = sns.FacetGrid(df, col="Region", col_wrap=3, height=4)
    g.map_dataframe(sns.scatterplot, x="Precio_Unitario", y="Total", alpha=0.6, color="#4C72B0")
    g.set_axis_labels("Precio Unitario (€)", "Total (€)")
    g.fig.suptitle("Relación Precio Unitario vs Total por Región", fontsize=16)
    g.fig.subplots_adjust(top=0.85)
    plt.show()


    print("\n--- Evaluación de posibles correlaciones espurias ---")

    from scipy.stats import pearsonr

    # Ejemplo: análisis de desempeño por Vendedor (variable categórica).

    plt.figure(figsize=(10,6))
    sns.boxplot(data=df, x="Vendedor", y="Total", palette="Set2")
    plt.title("Distribución del Total por Vendedor", fontsize=14)
    plt.xticks(rotation=45)
    plt.show()

    print("Se analiza Vendedor como variable categórica (correcto).")
    print("No se aplica correlación directa porque no es variable numérica continua.")

    # Ejemplo de correlación espuria (una relación NO válida).
    # Analizamos de forma específica estas variables, es por eso que debemos hacer los cálculos.

    print("\nSimulación de correlación espuria codificando Vendedor")

    df["Vendedor_cod"] = df["Vendedor"].astype("category").cat.codes

    r_spur, p_spur = pearsonr(df["Vendedor_cod"], df["Total"])

    print("Coeficiente de Pearson (Vendedor codificado vs Total):", r_spur)
    print("Valor p:", p_spur)

    print("\nInterpretación:")
    print("Esta correlación es ESPURIA.")
    print("El código numérico asignado al vendedor es arbitrario y no representa una magnitud económica.")
    print("Por lo tanto, no debe interpretarse como relación real.")

    # Eliminamos la columna auxiliar para no contaminar los análisis posteriores.
    df.drop(columns=["Vendedor_cod"], inplace=True)

    return df


# LECCIÓN 6 – LIBRERÍA MATPLOTLIB

def matpl_datos(df):

    print("\n========== LECCIÓN 6 – LIBRERÍA MATPLOTLIB ==========")

    # Importamos PdfPages para guardar múltiples gráficos en un solo PDF.
    # Tuve el deber de investigar ya que sin esto el documento final aparece en blanco.

    from matplotlib.backends.backend_pdf import PdfPages

    with PdfPages("analisis_final_ventas.pdf") as pdf:

        # Generamos un histograma que resuma la frecuencia con la totalidad de ventas.
        # Para la personalización nos tocó averiguar acerca de las especificaciones.

        fig1, ax1 = plt.subplots(figsize=(8, 5))
        ax1.hist(df["Total"], bins=20, color="#55a868", edgecolor="black")
        ax1.set_title("Distribución del total de ventas")
        ax1.set_xlabel("Total (€)")
        ax1.set_ylabel("Frecuencia")

        pdf.savefig(fig1)
        plt.show()
        plt.close(fig1)

        # Entregamos un scatter que demuestre la relacion entre la Cantidad y el total.
        # Para la personalización nos tocó averiguar acerca de las especificaciones.

        fig2, ax2 = plt.subplots(figsize=(8, 5))
        ax2.scatter(df["Cantidad"], df["Total"], alpha=0.6, color="#c44e52")
        ax2.set_title("Cantidad vs Total")
        ax2.set_xlabel("Cantidad")
        ax2.set_ylabel("Total (€)")

        pdf.savefig(fig2)
        plt.show()
        plt.close(fig2)

        # Usamos un gráfico de barras que entregue las Ventas por Categoría y Región.
        # Para la personalización nos tocó averiguar acerca de las especificaciones.

        fig3 = plt.figure(figsize=(12, 6))
        sns.barplot(data=df, x="Categoria", y="Total", hue="Region", estimator=sum, errorbar=None)
        plt.title("Ventas Totales por Categoría y Región", fontsize=15)
        plt.ylabel("Euros Totales (€)")
        plt.legend(title="Región", bbox_to_anchor=(1.05, 1), loc='upper left')

        pdf.savefig(fig3)
        plt.show()
        plt.close(fig3)

        # Por medio de un gráfico boxplot medimos el rendimiento por Vendedor para comparar las ventas realizadas.
        # Para la personalización nos tocó averiguar acerca de las especificaciones.

        fig4 = plt.figure(figsize=(10, 5))
        order = df.groupby("Vendedor")["Total"].sum().sort_values(ascending=False).index
        sns.boxplot(data=df, x="Vendedor", y="Total", order=order, palette="Set2")
        plt.title("Rendimiento y Consistencia de Vendedores", fontsize=14)

        pdf.savefig(fig4)
        plt.show()
        plt.close(fig4)

        # Finalmente podemos hacer un análisis de Tipo de Cliente que acude a las tiendas.
        # Para la personalización nos tocó averiguar acerca de las especificaciones.

        fig5 = plt.figure(figsize=(8, 5))
        sns.countplot(data=df, x="Cliente", palette="pastel")
        plt.title("Distribución de Clientes (Nuevos vs Recurrentes)")

        pdf.savefig(fig5)
        plt.show()
        plt.close(fig5)

    print("PDF generado correctamente: analisis_final_ventas.pdf")

    return df


# FUNCIÓN PRINCIPAL

def main():

    df = pd.read_csv("Ventas_sucursales_espana_50_filas_realista_v2.csv")

    df = analisis_datos(df)
    df = estad_desc(df)
    df = correlac_data(df)
    df = regres_lineal(df)
    df = visual_data(df)
    df = matpl_datos(df)

    print("\nPROCESO COMPLETADO EXITOSAMENTE")
    print("¡GRACIAS POR REVISAR MI CÓDIGO!")
    print("ANTE DUDAS ACERCA DEL PROCESO O CONCLUSIONES TE INVITO A REVISAR LOS DOCUMENTOS ADJUNTOS")


if __name__ == "__main__":
    main()

#-------------------------------------------------------------
# PROYECTO MÓDULO 5 POR SJV
# Dataset: Ventas_sucursales_espana_50_filas_realista_v2.csv
# En este proyecto se siguió el orden de las lecciones indicadas en el documento
# Espero que el orden y sintaxis sea adecuado, me base en las lecciones anteriores
# así como también algunos documentos entregados como apoyo de estudio.
# Algunos elementos tuve que obtenerlos de lectura/recursos complementarios.
#-------------------------------------------------------------

# LIBRERÍAS A UTILIZAR EN ESTE PROYECTO

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# DECIDI ASISGNAR UNA TEMÁTICA GENERAL A LOS GRÁFICOS PARA QUE SIGAN UNA MISMA LÍNEA.
sns.set_theme(
    style="whitegrid",
    palette="Set2",
    context="notebook")

# LECCIÓN 1 – ANÁLISIS EXPLORATORIO DE DATOS.

def analisis_datos(df):

    print("\n========== LECCIÓN 1 – ANÁLISIS EXPLORATORIO DE DATOS ==========")

    # Para leer las primeras filas usamos head.
    print("\nPrimeras filas:")
    print(df.head())

    # Para leer las últimas filas usamos tail.
    print("\nÚltimas filas:")
    print(df.tail())

    # Si deseamos saber la info general usamos info.
    print("\nInformación general:")
    df.info()

    # Para tener una descripción del database usamos describe.
    print("\nEstadísticas descriptivas:")
    print(df.describe())

    # Incluimos una descripción de los objetos al especificarlo entre paréntesis.
    print("\nDescripción de objetos:")
    print(df.describe(include="object"))

    # Importante definir el tipo de variables con las que vamos a trabajar.

    print("Variables numéricas:", df.select_dtypes(include="number").columns)
    print("Variables categóricas:", df.select_dtypes(include="object").columns)

    # Si hay valores nulos dentro de los daros podemos obtenerlos con:
    print("\nValores nulos:")
    print(df.isnull().sum())

    # Estos valores serán tratados a través de la función:
    print("\nEliminación de valores nulos:", df.shape)
    df.dropna(inplace=True)
    print("\nValores nulos eliminados:", df.shape)

    return df


# LECCIÓN 2 – CONCEPTOS BÁSICOS DE ESTADÍSTICA DESCRIPTIVA

def estad_desc(df):

    print("\n========== LECCIÓN 2 – ESTADÍSTICA DESCRIPTIVA ==========")

    # Excluimos ID_Venta como variable ya que no tiene un sentido estadístico en los cálculos.
    numeric_df = df.select_dtypes(include=np.number).drop(columns=["ID_Venta"], errors="ignore")

    # Podemos definir las medidas de tendencia central y de dispersión con:
    print("Media:\n", numeric_df.mean())
    print("Mediana:\n", numeric_df.median())
    print("Moda:\n", numeric_df.mode())
    print("Varianza:\n", numeric_df.var())
    print("Desviación std:\n", numeric_df.std())

    # Calculamos los cuartiles o percentiles a través de:
    print("Cuartiles:\n", numeric_df.quantile([0.25, 0.5, 0.75]))

    # Para conocer la frecuencia de algo podemos usar un histograma para represemtarlo:
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    numeric_df.hist(figsize=(12, 8), bins=20, edgecolor="black", color="#FF0000")
    plt.suptitle("Distribución de variables numéricas", fontsize=16)
    plt.show()

    # Para detectar valores atípicos (outliers) podemos usar un gráfico boxplot:
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    plt.figure(figsize=(12, 6))
    sns.boxplot(
        data=numeric_df,
        palette="Set3")
    plt.title("Detección de valores atípicos en variables numéricas", fontsize=14)
    plt.xticks(rotation=45)
    plt.show()

    return df


# LECCIÓN 3 – CORRELACIÓN

def correlac_data(df):

    print("\n========== LECCIÓN 3 – CORRELACIÓN ==========")

    from scipy.stats import pearsonr

    # Decidimos convertir las variables a numéricas por seguridad de los cálculos.

    df["Cantidad"] = pd.to_numeric(df["Cantidad"], errors="coerce")
    df["Precio_Unitario"] = pd.to_numeric(df["Precio_Unitario"], errors="coerce")
    df["Total"] = pd.to_numeric(df["Total"], errors="coerce")

    # Excluimos ID_Venta para que no afecte la correlación

    numeric_df = df.select_dtypes(include=np.number).drop(columns=["ID_Venta"], errors="ignore")

    # Podemos crear una Matriz de correlación general que se represente por un heatmap:
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    plt.figure(figsize=(8,6))
    sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm", linewidths=0.5)
    plt.title("Matriz de Correlación", fontsize=14)
    plt.show()

    # Aplicamos el coeficiente de Pearson para cuantificar la correlación entre variables:
    # Creamos dos cálculos para tener un mayor conocimiento del estado y así comparar.

    # Cantidad vs Total
    r1, p1 = pearsonr(df["Cantidad"], df["Total"])

    print("\nCantidad vs Total")
    print("Coeficiente de Pearson:", r1)
    print("Valor p:", p1)

    # Precio_Unitario vs Total
    r2, p2 = pearsonr(df["Precio_Unitario"], df["Total"])

    print("\nPrecio_Unitario vs Total")
    print("Coeficiente de Pearson:", r2)
    print("Valor p:", p2)

    # Interpretación automática de los datos obtenidos en esta sección:

    def interpretar(r, p, variable):
        if abs(r) > 0.7:
            fuerza = "fuerte"
        elif abs(r) > 0.4:
            fuerza = "moderada"
        else:
            fuerza = "débil"

        if p < 0.05:
            significancia = "Estadísticamente significativa"
        else:
            significancia = "Estadísticamente NO significativa"

        print(f"Correlación {fuerza} y {significancia} para {variable}")

    interpretar(r1, p1, "Cantidad")
    interpretar(r2, p2, "Precio_Unitario")

    return df


# LECCIÓN 4 – REGRESIONES LINEALES

def regres_lineal(df):

    print("\n========== LECCIÓN 4 – REGRESIONES LINEALES ==========")

    # Necesitaremos acudir a statsmodels para poder crear una regresión lineal
    # Así mismo llamaremos al cálculo de elementos fundamentales.

    import statsmodels.api as sm
    from sklearn.metrics import mean_squared_error, mean_absolute_error

    # Regresión simple (Cantidad - Total)
    X_simple = sm.add_constant(df["Cantidad"])
    y = df["Total"]

    model_simple = sm.OLS(y, X_simple).fit()

    print("\n--- Regresión Simple (Cantidad - Total) ---")
    print(model_simple.summary())

    # Acudimos a seaborn.regplot para generar una visualización de esta relación.
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    plt.figure(figsize=(8, 6))
    sns.regplot(
        x="Cantidad",
        y="Total",
        data=df,
        scatter_kws={"alpha": 0.5, "color": "#4C72B0"},
        line_kws={"color": "red", "linewidth": 2})
    plt.title("Regresión lineal: Cantidad vs Total", fontsize=14)
    plt.xlabel("Cantidad")
    plt.ylabel("Total (€)")
    plt.show()

    pred_simple = model_simple.predict(X_simple)

    # Podemos evaluar el modelo con los siguientes parámetros de prueba:

    print("MSE:", mean_squared_error(y, pred_simple))
    print("MAE:", mean_absolute_error(y, pred_simple))
    print("R2:", model_simple.rsquared)


    # Regresión múltiple (Cantidad - Precio_Unitario - Total)

    X_multiple = df[["Cantidad", "Precio_Unitario"]]
    X_multiple = sm.add_constant(X_multiple)

    model_multiple = sm.OLS(y, X_multiple).fit()

    print("\n--- Regresión Múltiple (Cantidad + Precio_Unitario → Total) ---")
    print(model_multiple.summary())
    print("R2 modelo múltiple:", model_multiple.rsquared)

    return df


# LECCIÓN 5 – ANÁLISIS VISUAL DE DATOS

def visual_data(df):

    print("\n========== LECCIÓN 5 – ANÁLISIS VISUAL DE DATOS ==========")

    # Excluimos ID_Venta de las visualizaciones numéricas
    numeric_df = df.select_dtypes(include=np.number).drop(columns=["ID_Venta"], errors="ignore")

    # Podemos crear un gráfico con Pairplot personalizado para detectar patrones.
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    g = sns.pairplot(
        numeric_df,
        corner=True,
        diag_kind="kde",
        plot_kws={"alpha": 0.6, "color": "#4C72B0"},
        diag_kws={"color": "#55a868"})
    g.fig.suptitle("Relaciones entre variables numéricas", fontsize=16)
    g.fig.subplots_adjust(top=0.95)
    plt.show()

    # Mismo caso con Jointplot personalizado para detectar patrones.
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    g = sns.jointplot(
        data=df,
        x="Cantidad",
        y="Total",
        kind="reg",
        height=7,
        scatter_kws={"alpha": 0.5, "color": "#4C72B0"},
        line_kws={"color": "red", "linewidth": 2})
    g.fig.suptitle("Cantidad vs Total", fontsize=14)
    g.fig.subplots_adjust(top=0.95)
    plt.show()

    # Existe el elemento Violinplot para el cálculo de densidad, en este caso de las ventas por sucursal.
    # Para la personalización nos tocó averiguar acerca de las especificaciones.

    plt.figure(figsize=(10, 5))
    sns.violinplot(
    data=df,
    x="Sucursal",
    y="Total",
    inner="quart",
    palette="Set2")
    plt.title("Densidad de Ventas por Sucursal")
    plt.show()

  # Finalmente usamos FacetGrid para una segmentación por Región.
  # Para la personalización nos tocó averiguar acerca de las especificaciones.

    g = sns.FacetGrid(df, col="Region", col_wrap=3, height=4)
    g.map_dataframe(
        sns.scatterplot,
        x="Precio_Unitario",
        y="Total",
        alpha=0.6,
        color="#4C72B0")
    g.set_axis_labels("Precio Unitario (€)", "Total (€)")
    g.fig.suptitle("Relación Precio Unitario vs Total por Región", fontsize=16)
    g.fig.subplots_adjust(top=0.85)
    plt.show()


    print("\n--- Evaluación de posibles correlaciones espurias ---")

    from scipy.stats import pearsonr

    # Ejemplo correcto: análisis de desempeño por Vendedor (variable categórica)

    plt.figure(figsize=(10,6))
    sns.boxplot(
        data=df,
        x="Vendedor",
        y="Total",
        palette="Set2")
    plt.title("Distribución del Total por Vendedor", fontsize=14)
    plt.xticks(rotation=45)
    plt.show()

    print("Se analiza Vendedor como variable categórica.")
    print("No se aplica correlación directa porque no es variable numérica continua.")

    # Ejemplo de correlación espuria (Una correlación NO válida).

    print("\nSimulación de correlación espuria codificando Vendedor...")

    df["Vendedor_cod"] = df["Vendedor"].astype("category").cat.codes

    r_spur, p_spur = pearsonr(df["Vendedor_cod"], df["Total"])

    print("Coeficiente de Pearson (Vendedor codificado vs Total):", r_spur)
    print("Valor p:", p_spur)

    print("\nInterpretación:")
    print("Esta correlación es ESPURIA.")
    print("El código numérico asignado al vendedor es arbitrario y no representa una magnitud económica.")
    print("Por lo tanto, no debe interpretarse como relación real.")

    # Eliminamos la columna auxiliar para no contaminar los análisis posteriores.
    df.drop(columns=["Vendedor_cod"], inplace=True)

    return df


# LECCIÓN 6 – LIBRERÍA MATPLOTLIB

def matpl_datos(df):

    print("\n========== LECCIÓN 6 – LIBRERÍA MATPLOTLIB ==========")

    # Importamos PdfPages para guardar múltiples gráficos en un solo PDF.
    # Tuve que averiguar este elemento, ya que sin él, el documento saldría en blanco.

    from matplotlib.backends.backend_pdf import PdfPages

    with PdfPages("analisis_final_ventas.pdf") as pdf:

        # Generamos un histograma que resuma la frecuencia vs la totalidad de ventas.

        fig1, ax1 = plt.subplots(figsize=(8, 5))
        ax1.hist(df["Total"], bins=20, color="#55a868", edgecolor="black")
        ax1.set_title("Distribución del total de ventas")
        ax1.set_xlabel("Total (€)")
        ax1.set_ylabel("Frecuencia")

        pdf.savefig(fig1)
        plt.show()
        plt.close(fig1)

        # Entregamos un scatter que demuestre la relacion entre la Cantidad y el total.

        fig2, ax2 = plt.subplots(figsize=(8, 5))
        ax2.scatter(df["Cantidad"], df["Total"], alpha=0.6, color="#c44e52")
        ax2.set_title("Cantidad vs Total")
        ax2.set_xlabel("Cantidad")
        ax2.set_ylabel("Total (€)")

        pdf.savefig(fig2)
        plt.show()
        plt.close(fig2)

        # Decidi averiguar sobre otros gráficos que podría incluir para sumas al análisis:

        # Gráfico de barras que representa las Ventas por Categoría y Región (Segmentación)
        # para verificar geograficamente las diferencias.

        fig3 = plt.figure(figsize=(12, 6))
        sns.barplot(data=df, x="Categoria", y="Total", hue="Region", estimator=sum, errorbar=None)
        plt.title("Ventas Totales por Categoría y Región", fontsize=15)
        plt.ylabel("Euros Totales (€)")
        plt.legend(title="Región", bbox_to_anchor=(1.05, 1), loc='upper left')

        pdf.savefig(fig3)
        plt.show()
        plt.close(fig3)

        # Gráfico boxplot que mide el rendimiento por Vendedor para comparar las Ventas realizadas.

        fig4 = plt.figure(figsize=(10, 5))
        order = df.groupby("Vendedor")["Total"].sum().sort_values(ascending=False).index
        sns.boxplot(data=df, x="Vendedor", y="Total", order=order, palette="Set2")
        plt.title("Rendimiento y Consistencia de Vendedores", fontsize=14)

        pdf.savefig(fig4)
        plt.show()
        plt.close(fig4)

        # Gráfico que demuestra el Tipo de Cliente que acude a las diversas tiendas.

        fig5 = plt.figure(figsize=(8, 5))
        sns.countplot(data=df, x="Cliente", palette="pastel")
        plt.title("Distribución de Clientes (Nuevos vs Recurrentes)")

        pdf.savefig(fig5)
        plt.show()
        plt.close(fig5)

    print("PDF generado correctamente: analisis_final_ventas.pdf")

    return df


# FUNCIÓN PRINCIPAL

def main():

    df = pd.read_csv("Ventas_sucursales_espana_50_filas_realista_v2.csv")

    df = analisis_datos(df)
    df = estad_desc(df)
    df = correlac_data(df)
    df = regres_lineal(df)
    df = visual_data(df)
    df = matpl_datos(df)

    print("\nPROCESO COMPLETADO EXITOSAMENTE")


if __name__ == "__main__":
    main()